iot-collector:
  image: wjglerum/iot-collector:1.0-WS-2018
  container_name: iot-collector
  environment:
    - PLAY_SECRET=1308tuy203w8ytq3ut0q32t
  ports:
    - "9000:9000"
  links:
    - mosquitto

mosquitto:
  image: eclipse-mosquitto
  container_name: mosquitto
  ports:
  - "1883:1883"
