{
 "title": "IoT",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "energy_sensor_id", "query": "1" },
   { "name": "zone_id", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Weather",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather_outside",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "tado" }
     ]
    },
    {
     "alias": "Solar Intensity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather_outside",
     "select": [
      [
       { "params": [ "solarIntensity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "tado" }
     ]
    }
   ]
  },
  {
   "title": "Thermostat",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "repeat": "zone_id",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "thermostat",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "tado" },
      { "condition": "AND", "key": "zone", "operator": "=~", "value": "/^$zone_id$/" }
     ]
    },
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "thermostat",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "tado" },
      { "condition": "AND", "key": "zone", "operator": "=~", "value": "/^$zone_id$/" }
     ]
    },
    {
     "alias": "HeatingPower",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "thermostat",
     "select": [
      [
       { "params": [ "heatingPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "tado" },
      { "condition": "AND", "key": "zone", "operator": "=~", "value": "/^$zone_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Energy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "repeat": "energy_sensor_id",
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "domoticz" },
      { "condition": "AND", "key": "sensorId", "operator": "=~", "value": "/^$energy_sensor_id$/" }
     ]
    },
    {
     "alias": "CounterToday",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "counterToday" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "domoticz" },
      { "condition": "AND", "key": "sensorId", "operator": "=~", "value": "/^$energy_sensor_id$/" }
     ]
    }
   ]
  }
 ]
}